version: "2"

services:
  django:
    container_name: jatumba_django
    restart: always
    build:
      context: jatumba-backend
      dockerfile: Dockerfile.django
    env_file: jatumba-backend/.env
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - /tmp/jatumba/gunicorn:/var/log/gunicorn
      - /usr/src/app/static

  daphne:
    container_name: jatumba_daphne
    restart: always
    build:
      context: jatumba-backend
      dockerfile: Dockerfile.daphne
    env_file: jatumba-backend/.env
    ports:
      - "9000:9000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - /tmp/jatumba/daphne:/var/log/daphne

  worker:
    container_name: jatumba_worker
    restart: always
    build:
      context: jatumba-backend
      dockerfile: Dockerfile.worker
    env_file: jatumba-backend/.env
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - /tmp/jatumba/worker:/var/log/worker

  frontend:
    container_name: jatumba_frontend
    restart: always
    build: jatumba-frontend

  nginx:
    container_name: jatumba_nginx
    restart: always
    build: jatumba-nginx
    ports:
      - "8080:80"
    volumes:
      - /www/static
    volumes_from:
      - django:ro
      - frontend:ro
    links:
      - django:django

  postgres:
    container_name: jatumba_postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/

  redis:
    container_name: jatumba_redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /data
