version: "3"

services:
  django:
    build:
      context: jatumba-backend
      dockerfile: Dockerfile.django
    container_name: jatumba_django
    depends_on:
      - postgres
      - redis
    env_file: .env
    external_links:
      - nginx:nginx
    links:
      - postgres:postgres
      - redis:redis
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - logs:/var/log/
      - static:/static
      - media:/media

  daphne:
    build:
      context: jatumba-backend
      dockerfile: Dockerfile.daphne
    container_name: jatumba_daphne
    depends_on:
      - postgres
      - redis
    env_file: .env
    external_links:
      - nginx:nginx
    links:
      - postgres:postgres
      - redis:redis
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - logs:/var/log/

  worker:
    build:
      context: jatumba-backend
      dockerfile: Dockerfile.worker
    container_name: jatumba_worker
    depends_on:
      - postgres
      - redis
    env_file: .env
    external_links:
      - nginx:nginx
    links:
      - postgres:postgres
      - redis:redis
    restart: always
    volumes:
      - logs:/var/log/

  frontend:
    build: jatumba-frontend
    container_name: jatumba_frontend
    volumes:
      - frontend-data:/frontend

  nginx:
    build:
      context: jatumba-nginx
      dockerfile: Dockerfile.dev
    container_name: jatumba_nginx
    depends_on:
      - frontend
    links:
      - django:django
      - daphne:daphne
    ports:
      - "3000:80"
    restart: always
    volumes:
      - static:/jatumba/backend/static
      - media:/jatumba/backend/media
      - frontend-data:/jatumba/frontend

  postgres:
    container_name: jatumba_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - posgres-data:/var/lib/postgresql/data/

  redis:
    container_name: jatumba_redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

volumes:
  logs:
  media:
  static:
  frontend-data:
  redis-data:
  posgres-data:
