version: "2"

services:
  django:
    container_name: jatumba_django
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.django
    env_file: .env
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - /var/log/jatumba/gunicorn:/var/log/gunicorn
      - /usr/src/app/static

  daphne:
    container_name: jatumba_daphne
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.daphne
    env_file: .env
    ports:
      - "9000:9000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - /var/log/jatumba/daphne:/var/log/daphne

  worker:
    container_name: jatumba_worker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file: .env
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - /var/log/jatumba/worker:/var/log/worker

  nginx:
    container_name: jatumba_nginx
    restart: always
    build: ./server_configurations/nginx/
    ports:
      - "8080:80"
    volumes:
      - /www/static
    volumes_from:
      - django
    links:
      - django:django

  postgres:
    container_name: jatumba_postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/

  redis:
    container_name: jatumba_redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /data
